In [ ]:
import pandas as pd
india_weather=pd.DataFrame({
    'city':['Raipur','Bhilai','Durg'],
    'Wind_speed':[30,44,55],
    "humidity": [80, 60, 78]
})
india_weather

     city  Wind_speed
0  Raipur          30
1  Bhilai          44
2    Durg          55

In [ ]:
import pandas as pd
us_weather=pd.DataFrame({
    'city':['New_Jersy','washington','White_house'],
    'Wind_speed':[30,44,55],
    "humidity": [80, 60, 78]
})
us_weather

          city  Wind_speed
0    New_Jersy          30
1   washington          44
2  White_house          55

In [ ]:
#pd.concat([us_weather,india_weather],axis=1)

          city  Wind_speed  humidity    city  Wind_speed  humidity
0    New_Jersy          30        80  Raipur          30        80
1   washington          44        60  Bhilai          44        60
2  White_house          55        78    Durg          55        78

In [36]:
df3=pd.merge(us_weather,india_weather,on='city',how='outer') 
df3

          city  Wind_speed_x  Wind_speed_y
0       Bhilai           NaN          44.0
1         Durg           NaN          55.0
2    New_Jersy          30.0           NaN
3       Raipur           NaN          30.0
4  White_house          55.0           NaN
5   washington          44.0           NaN