In [1]:
import pandas as pd
df=pd.read_csv("weather_data.csv")
new_df=df.interpolate()
new_df

C:\Users\KIIT\AppData\Local\Temp\ipykernel_15696\219967659.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df=df.interpolate()

         day  temperature  windspeed   event
0   1/1/2017         32.0      6.000    Rain
1   1/4/2017         30.0      9.000   Sunny
2   1/5/2017         28.0      8.000    Snow
3   1/6/2017         30.0      7.000     NaN
4   1/7/2017         32.0      7.275    Rain
5   1/8/2017         32.7      7.550   Sunny
6   1/9/2017         33.4      7.825     NaN
7  1/10/2017         34.1      8.100  Cloudy
8  1/11/2017         40.0     12.000   Sunny

In [21]:
import pandas as pd
df=pd.read_csv("weather_data.csv")
new_df=df.rename(columns={'event':"what_happened"})
new_df

         day  temperature  windspeed what_happened
0   1/1/2017         32.0        6.0          Rain
1   1/4/2017          NaN        9.0         Sunny
2   1/5/2017         28.0        NaN          Snow
3   1/6/2017          NaN        7.0           NaN
4   1/7/2017         32.0        NaN          Rain
5   1/8/2017          NaN        NaN         Sunny
6   1/9/2017          NaN        NaN           NaN
7  1/10/2017         34.1        8.1        Cloudy
8  1/11/2017         40.0       12.0         Sunny

In [ ]:
new_df=df.dropna(how="all")
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

: